# Publish to PyPi package index

name: PIP Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:

  publish:
    name: Publish to PyPi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Python Dependencies
        run: |
          pip install --upgrade build twine
      - name: Build Binary
        run: |
          python3 -m build
      - name: Publish
        run: |
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_REPOSITORY: pypi