# Publish to TestPyPi package index

name: Test PIP Publish

on: [push]

permissions:
  contents: read

jobs:

  test_publish:
    name: Publish to TestPyPi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Python Dependencies
        # pip install --upgrade wheel setuptools twine
        run: |
          pip install --upgrade build twine
      - name: Build Binary
        # python3 setup.py sdist bdist_wheel --universal
        run: |
          python3 -m build
      - name: Publish
        run: |
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
          TWINE_REPOSITORY: testpypi